import { describe, expect, it, vi, beforeEach } from "vitest";
import { promptsRouter } from "./prompts";
import type { TrpcContext } from "../_core/context";

// Mock the LLM module
vi.mock("../_core/llm", () => ({
  invokeLLM: vi.fn(async () => ({
    choices: [
      {
        message: {
          content: "This is a test prompt generated by the mock LLM.",
        },
      },
    ],
  })),
}));

type AuthenticatedUser = NonNullable<TrpcContext["user"]>;

function createAuthContext(): TrpcContext {
  const user: AuthenticatedUser = {
    id: 1,
    openId: "test-user",
    email: "test@example.com",
    name: "Test User",
    loginMethod: "manus",
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date(),
    lastSignedIn: new Date(),
  };

  return {
    user,
    req: {
      protocol: "https",
      headers: {},
    } as TrpcContext["req"],
    res: {} as TrpcContext["res"],
  };
}

describe("prompts router", () => {
  it(
    "generates a TikTok prompt",
    async () => {
    const ctx = createAuthContext();
    const caller = promptsRouter.createCaller(ctx);

    const result = await caller.generatePrompt({
      category: "tiktok",
    });

    expect(result.success).toBe(true);
    expect(result.prompt).toBeDefined();
    expect(result.prompt?.category).toBe("tiktok");
    expect(result.prompt?.content).toBeTruthy();
    expect(typeof result.prompt?.content).toBe("string");
    },
    { timeout: 10000 }
  );

  it(
    "generates a stream prompt with theme",
    async () => {
    const ctx = createAuthContext();
    const caller = promptsRouter.createCaller(ctx);

    const result = await caller.generatePrompt({
      category: "stream",
      theme: "void awakening",
    });

    expect(result.success).toBe(true);
    expect(result.prompt).toBeDefined();
    expect(result.prompt?.category).toBe("stream");
    expect(result.prompt?.theme).toBe("void awakening");
    expect(result.prompt?.content).toBeTruthy();
    },
    { timeout: 10000 }
  );

  it(
    "generates a horror prompt",
    async () => {
    const ctx = createAuthContext();
    const caller = promptsRouter.createCaller(ctx);

    const result = await caller.generatePrompt({
      category: "horror",
    });

    expect(result.success).toBe(true);
    expect(result.prompt).toBeDefined();
    expect(result.prompt?.category).toBe("horror");
    expect(result.prompt?.content).toBeTruthy();
    },
    { timeout: 10000 }
  );

  it(
    "includes generated timestamp",
    async () => {
    const ctx = createAuthContext();
    const caller = promptsRouter.createCaller(ctx);

    const result = await caller.generatePrompt({
      category: "tiktok",
    });

    expect(result.prompt?.generatedAt).toBeInstanceOf(Date);
    },
    { timeout: 10000 }
  );
});
